development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: azerteach
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>