development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: azerteach
  pool: 100
  username: root
  password: root
  host: localhost

production:
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
